CREATE OR ALTER PROCEDURE SP_AlterarBeneficiario
    @ID INT,
    @CPF NVARCHAR(11),
    @NOME NVARCHAR(50),
    @IDCLIENTE INT
AS
BEGIN
    UPDATE BENEFICIARIOS
    SET CPF = @CPF,
        NOME = @NOME,
        IDCLIENTE = @IDCLIENTE
    WHERE ID = @ID;
END;
